Repository ary1733/Hacktober2020, pull requests merged in 2020-10, with the labels that each got.

#1 Added number theory questions
  binary exponent loop.cpp
  binary exponent recursive.cpp
  et or pfi using seive way.cpp
  etf or phi in sqrt(n).cpp
  euclid extended.cpp
  euclidproblem.cpp
  gcd.cpp
  modular exponent loop.cpp
  modular exponent recursion.cpp
  no of div with seive.cpp
  no of div without seive.cpp
  primefactor using seive.cpp
  sum of all div using seive.cpp
  sum of all prime using seive.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#7 I have added code for factorical in python - Create factorial.py
  Python/factorial.py
Labels: hacktoberfest-accepted

#9 Create fibonacci.py
  Python/fibonacci.py
Labels: hacktoberfest-accepted

#10 Here is the basic CPP code to find the factorial.
  CPP/CPP factorial
Labels: hacktoberfest-accepted

#12 Create gcd.py
  Python/gcd.py
Labels: hacktoberfest-accepted

#13 Moved all .cpp files to CPP directory and also renamed them
  CPP/binary_exponent_loop.cpp
  CPP/binary_exponent_recursive.cpp
  CPP/et_or_pfi_using_seive_way.cpp
  CPP/etf_or_phi_in_sqrt(n).cpp
  CPP/euclid.cpp
  CPP/euclid_extended.cpp
  CPP/factorial.cpp
  CPP/gcd.cpp
  CPP/modular_exponent_loop.cpp
  CPP/modular_exponent_recursion.cpp
  CPP/no_of_div_with_seive.cpp
  CPP/no_of_div_without_seive.cpp
  CPP/primefactor_using_seive.cpp
  CPP/sum_of_all_div_using_seive.cpp
  CPP/sum_of_all_prime_using_seive.cpp
Labels: hacktoberfest-accepted

#18 added merge_sort.cpp file
  CPP/merge_sort.cpp
Labels: hacktoberfest-accepted

#19 Added DFS in CPP to the CPP directory
  CPP/dfs
Labels: hacktoberfest-accepted

#23 Create dfs.py
  Python/dfs.py
Labels: hacktoberfest, hacktoberfest-accepted

#22 Code Based on GeeksForGeeks documentation
  Python/Radix Sort Py
Labels: hacktoberfest, hacktoberfest-accepted

#21 merge sort in python
  Python/mergesort.py
Labels: hacktoberfest, hacktoberfest-accepted

#32 Added AVL Tree Implementation
  CPP/AVL.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#34 Added Calculator Implementation in C++
  CPP/Calculator.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#36 Finding Diameter of Tree
  CPP/TreeDia.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#38 dIJKSTRA ALGORITHM
  CPP/dijkstra.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#44 Add RadixSort.cpp
  CPP/Radixsort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#43 Python - Calculator Added
  Python/calculator.py
Labels: hacktoberfest, hacktoberfest-accepted

#42 Added segment tree
  CPP/segment_tree.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#46 Added Tic Tac Toe implementation in Python and Cpp.
  CPP/TopoSort.cpp
  CPP/tic_tac_toe.cpp
  Python/tic_tac_toe.py
Labels: hacktoberfest, hacktoberfest-accepted

#47 Graph
  Graphs/Breadth First Search Using STL Queue.txt
  Graphs/Depth First Search Using Recursion.txt
  Graphs/Depth First Search Using STL Stack.txt
  Graphs/Krushals Min Cost Spanning Tree.txt
  Graphs/Prim Min Spanning Tree.txt
Labels: hacktoberfest, hacktoberfest-accepted

#49 Create Cycle Detection In Graph.cpp
  CPP/Cycle Detection In Graph.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#48 RadixSort.cpp
  CPP/RadixSort.cpp
Labels: duplicate

#41 Add simple_calculator.py
  Python/simple_calculator.py
Labels: hacktoberfest, hacktoberfest-accepted

#33 Create calc.py
  Python/calc.py
Labels: duplicate

#50 Add in tic tac toe done in ReactJS
  .DS_Store
  Javascript/.DS_Store
  Javascript/tic-tac-toe-reactjs/.DS_Store
  Javascript/tic-tac-toe-reactjs/README.md
  Javascript/tic-tac-toe-reactjs/tic-tac-toe/.gitignore
  Javascript/tic-tac-toe-reactjs/tic-tac-toe/README.md
  Javascript/tic-tac-toe-reactjs/tic-tac-toe/build/asset-manifest.json
  Javascript/tic-tac-toe-reactjs/tic-tac-toe/build/favicon.ico
  Javascript/tic-tac-toe-reactjs/tic-tac-toe/build/index.html
  Javascript/tic-tac-toe-reactjs/tic-tac-toe/build/logo192.png
  Javascript/tic-tac-toe-reactjs/tic-tac-toe/build/logo512.png
  Javascript/tic-tac-toe-reactjs/tic-tac-toe/build/manifest.json
  Javascript/tic-tac-toe-reactjs/tic-tac-toe/build/precache-manifest.1b000d2f1f0e86d8ac59204baeb12efe.js
  Javascript/tic-tac-toe-reactjs/tic-tac-toe/build/robots.txt
  Javascript/tic-tac-toe-reactjs/tic-tac-toe/build/service-worker.js
  Javascript/tic-tac-toe-reactjs/tic-tac-toe/build/static/css/main.3fa7586b.chunk.css
  Javascript/tic-tac-toe-reactjs/tic-tac-toe/build/static/css/main.3fa7586b.chunk.css.map
  Javascript/tic-tac-toe-reactjs/tic-tac-toe/build/static/js/2.b9926c31.chunk.js
  Javascript/tic-tac-toe-reactjs/tic-tac-toe/build/static/js/2.b9926c31.chunk.js.LICENSE.txt
  Javascript/tic-tac-toe-reactjs/tic-tac-toe/build/static/js/2.b9926c31.chunk.js.map
  Javascript/tic-tac-toe-reactjs/tic-tac-toe/build/static/js/main.d8dd475c.chunk.js
  Javascript/tic-tac-toe-reactjs/tic-tac-toe/build/static/js/main.d8dd475c.chunk.js.map
  Javascript/tic-tac-toe-reactjs/tic-tac-toe/build/static/js/runtime-main.43a7c523.js
  Javascript/tic-tac-toe-reactjs/tic-tac-toe/build/static/js/runtime-main.43a7c523.js.map
  Javascript/tic-tac-toe-reactjs/tic-tac-toe/package-lock.json
  Javascript/tic-tac-toe-reactjs/tic-tac-toe/package.json
  Javascript/tic-tac-toe-reactjs/tic-tac-toe/public/favicon.ico
  Javascript/tic-tac-toe-reactjs/tic-tac-toe/public/index.html
  Javascript/tic-tac-toe-reactjs/tic-tac-toe/public/logo192.png
  Javascript/tic-tac-toe-reactjs/tic-tac-toe/public/logo512.png
  Javascript/tic-tac-toe-reactjs/tic-tac-toe/public/manifest.json
  Javascript/tic-tac-toe-reactjs/tic-tac-toe/public/robots.txt
  Javascript/tic-tac-toe-reactjs/tic-tac-toe/src/index.css
  Javascript/tic-tac-toe-reactjs/tic-tac-toe/src/index.js
Labels: hacktoberfest, hacktoberfest-accepted

#54 Added a python3 covid19-tracker.
  Python/covid-tracker.py
Labels: hacktoberfest, hacktoberfest-accepted

#53 Hashing
  CPP/DoubleHashingC++.txt
  CPP/Hash Table Class Chaining.txt
  CPP/Hash Table Quadratic Probing.txt
  CPP/HashTableLinearProbingC++.txt
  DoubleHashingC++.txt
  Hash Table Class Chaining.txt
  Hash Table Quadratic Probing.txt
  HashTableLinearProbingC++.txt
Labels: hacktoberfest, hacktoberfest-accepted

#52 added kosaraju's algorithm
  CPP/Kosaraju's Algorithm.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#55 Create Codeforces Round #486 Sub Strings Sort
  CPP/Codeforces Round #486 Sub Strings Sort
Labels: hacktoberfest, hacktoberfest-accepted

#63 Create Kana and Dragon Quest Game Codeforces
  CPP/Kana and Dragon Quest Game Codeforces
Labels: codeforces

#62 Create Nastya and Rice Codeforces
  CPP/Nastya and Rice
Labels: codeforces

#61 Create Registration System CodeForces
  CPP/Registration System CodeForces
Labels: codeforces

#60 Create Edgy Tree Codeforces
  CPP/Edgy Tree Codeforces
Labels: codeforces

#67 Added ConvToRevPol.cpp and PolEval.cpp
  CPP/ConvToRevPol.cpp
  CPP/PolEval.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#68 fibonacci.cpp
  CPP/fibonacci.cpp
  CPP/phone.cpp
Labels: good first issue

#69 adding URI problem answer (Door Lock) in c++
  CPP/DoorLock.cpp
Labels: Online Judge

#81 floyd algorithm in c++
  CPP/floyd_algorithm.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#79 Create Drchef.cpp
  CPP/Drchef.cpp
Labels: Online Judge

#82 Add files via upload
  java/hailstone.java
Labels: hacktoberfest, hacktoberfest-accepted

#88 DijkstraAlgorithm - Java
  java/Dijkstra.java
Labels: hacktoberfest, hacktoberfest-accepted

#90 Added new algorithm
  ToDo.md
Labels: hacktoberfest, hacktoberfest-accepted

#92 Added 256 SHA hashing
  Python/sha256Hash.py
Labels: hacktoberfest, hacktoberfest-accepted

#89 Added code
  CPP/advance_pattern1.cpp
  CPP/advance_pattern2.cpp
  CPP/advance_pattern3.cpp
  CPP/advance_pattern4.cpp
  CPP/advance_pattern5.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#74 Create disjointSet.cpp
  CPP/disjointSet.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#87 jainayu: Easy to understand Trie implementation.
  CPP/Trie.cpp
Labels: hacktoberfest, hacktoberfest-accepted
